name: Test & Deploy on Digital Ocean
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: cd src && go test ./...

  deploy:
    needs: test
    runs-on: ubuntu-latest
    # Deploy only when pushing onto main (or merging PR)
    if: github.event_name == 'push' && ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          user: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_KEY }}
          command: |
            cd /comiditapp-pruebas
            echo 'hello from github actions' >> message.txt
          args: "-tt"
